apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2023-03-08T11:40:40Z"
  generation: 1
  managedFields:
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:exclude.release.openshift.io/internal-openshift-hosted: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"e60de632-2954-4109-a630-deda141a29af"}: {}
      f:spec: {}
    manager: cluster-version-operator
    operation: Update
    time: "2023-03-08T11:40:40Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:extension: {}
    manager: cluster-version-operator
    operation: Update
    subresource: status
    time: "2023-03-08T11:40:41Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions: {}
        f:relatedObjects: {}
        f:versions: {}
    manager: authentication-operator
    operation: Update
    subresource: status
    time: "2023-03-08T11:57:49Z"
  name: authentication
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: e60de632-2954-4109-a630-deda141a29af
  resourceVersion: "24414"
  uid: 9fc24524-59af-49df-872f-a2431ffee4b2
spec: {}
status:
  conditions:
  - lastTransitionTime: "2023-03-08T11:47:24Z"
    message: "APIServerDeploymentDegraded: 1 of 3 requested instances are unavailable
      for apiserver.openshift-oauth-apiserver ()\nCustomRouteControllerDegraded: the
      server is currently unable to handle the request (get routes.route.openshift.io
      oauth-openshift)\nIngressStateEndpointsDegraded: No subsets found for the endpoints
      of oauth-server\nOAuthClientsControllerDegraded: no ingress for host oauth-openshift.apps.vrutkovs.origin-gce.dev.openshift.com
      in route oauth-openshift in namespace openshift-authentication\nOAuthServerDeploymentDegraded:
      waiting for the oauth-openshift route to contain an admitted ingress: no admitted
      ingress for route oauth-openshift in namespace openshift-authentication\nOAuthServerDeploymentDegraded:
      \nOAuthServerRouteEndpointAccessibleControllerDegraded: route \"openshift-authentication/oauth-openshift\":
      status does not have a valid host address\nOAuthServerServiceEndpointAccessibleControllerDegraded:
      Get \"https://172.30.73.115:443/healthz\": dial tcp 172.30.73.115:443: connect:
      connection refused\nOAuthServerServiceEndpointsEndpointAccessibleControllerDegraded:
      oauth service endpoints are not ready\nWellKnownReadyControllerDegraded: failed
      to get oauth metadata from openshift-config-managed/oauth-openshift ConfigMap:
      configmap \"oauth-openshift\" not found (check authentication operator, it is
      supposed to create this)"
    reason: APIServerDeployment_UnavailablePod::CustomRouteController_SyncError::IngressStateEndpoints_MissingSubsets::OAuthClientsController_SyncError::OAuthServerDeployment_PreconditionNotFulfilled::OAuthServerRouteEndpointAccessibleController_SyncError::OAuthServerServiceEndpointAccessibleController_SyncError::OAuthServerServiceEndpointsEndpointAccessibleController_SyncError::WellKnownReadyController_SyncError
    status: "True"
    type: Degraded
  - lastTransitionTime: "2023-03-08T11:52:05Z"
    message: 'AuthenticatorCertKeyProgressing: All is well'
    reason: AsExpected
    status: "False"
    type: Progressing
  - lastTransitionTime: "2023-03-08T11:45:21Z"
    message: |-
      OAuthServerServiceEndpointAccessibleControllerAvailable: Get "https://172.30.73.115:443/healthz": dial tcp 172.30.73.115:443: connect: connection refused
      OAuthServerServiceEndpointsEndpointAccessibleControllerAvailable: endpoints "oauth-openshift" not found
      WellKnownAvailable: The well-known endpoint is not yet available: failed to get oauth metadata from openshift-config-managed/oauth-openshift ConfigMap: configmap "oauth-openshift" not found (check authentication operator, it is supposed to create this)
    reason: OAuthServerDeployment_PreconditionNotFulfilled::OAuthServerServiceEndpointAccessibleController_EndpointUnavailable::OAuthServerServiceEndpointsEndpointAccessibleController_ResourceNotFound::WellKnown_NotReady
    status: "False"
    type: Available
  - lastTransitionTime: "2023-03-08T11:45:21Z"
    message: All is well
    reason: AsExpected
    status: "True"
    type: Upgradeable
  extension: null
  relatedObjects:
  - group: operator.openshift.io
    name: cluster
    resource: authentications
  - group: config.openshift.io
    name: cluster
    resource: authentications
  - group: config.openshift.io
    name: cluster
    resource: infrastructures
  - group: config.openshift.io
    name: cluster
    resource: oauths
  - group: route.openshift.io
    name: oauth-openshift
    namespace: openshift-authentication
    resource: routes
  - group: ""
    name: oauth-openshift
    namespace: openshift-authentication
    resource: services
  - group: ""
    name: openshift-config
    resource: namespaces
  - group: ""
    name: openshift-config-managed
    resource: namespaces
  - group: ""
    name: openshift-authentication
    resource: namespaces
  - group: ""
    name: openshift-authentication-operator
    resource: namespaces
  - group: ""
    name: openshift-ingress
    resource: namespaces
  - group: ""
    name: openshift-oauth-apiserver
    resource: namespaces
  versions:
  - name: operator
    version: 4.12.0-0.okd-2023-03-04-063026
  - name: oauth-apiserver
    version: 4.12.0-0.okd-2023-03-04-063026
